name: .NET Tests
on:
  push:

permissions:
  actions: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Invoke Staging Deployment
        if: github.ref == 'refs/heads/main'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "deploy-staging.yaml"
          
      - name: Invoke Prod Deployment
        if: github.ref == 'refs/heads/main'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "deploy-prod.yaml"

      - name: Invoke Dev Deployment
        if: github.ref == 'refs/heads/dev'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "deploy-dev.yaml"
