name: .NET Tests
on:
  push:

permissions:
    workflows: ['deploy-dev.yaml', 'deploy-staging.yaml', 'deploy-prod.yaml']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "deploy-staging.yaml"
